name: Trigger Scraper

on:
  schedule:
    - cron: "0 */3 * * *" #3 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to start scraping process
        env:
          SCRAPER_URL: ${{ secrets.SCRAPER_URL }}
          SCRAPER_TOKEN: ${{ secrets.SCRAPER_TOKEN }}
        run: |
          curl -X GET $SCRAPER_URL -H "Authorization: Bearer $SCRAPER_TOKEN"
